"""add mfa_failed_attempts, mfalocked_until

Revision ID: 0185b58ff6b2
Revises: b2c3d4e5f6a7
Create Date: 2026-05-19 14:48:49.416576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0185b58ff6b2'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_issues_client_id'), table_name='event_issues')
    op.drop_index(op.f('ix_event_issues_event_id'), table_name='event_issues')
    op.drop_index(op.f('ix_event_issues_open'), table_name='event_issues', postgresql_where='((resolved_at IS NULL) AND (deleted = false))')
    op.drop_column('payments', 'period_covered')
    op.drop_constraint(op.f('uq_scheduler_process_name'), 'scheduler_status', type_='unique')
    op.add_column('users', sa.Column('mfa_failed_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('mfa_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_locked_until')
    op.drop_column('users', 'mfa_failed_attempts')
    op.create_unique_constraint(op.f('uq_scheduler_process_name'), 'scheduler_status', ['process_name'], postgresql_nulls_not_distinct=False)
    op.add_column('payments', sa.Column('period_covered', postgresql.DATERANGE(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_event_issues_open'), 'event_issues', ['client_id', 'resolved_at'], unique=False, postgresql_where='((resolved_at IS NULL) AND (deleted = false))')
    op.create_index(op.f('ix_event_issues_event_id'), 'event_issues', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_issues_client_id'), 'event_issues', ['client_id'], unique=False)
    # ### end Alembic commands ###
