"""verify_sync

Revision ID: 206e1bd60058
Revises: 3f8ee520a1c2
Create Date: 2026-06-12 09:16:52.607782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206e1bd60058'
down_revision: Union[str, Sequence[str], None] = '3f8ee520a1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_account_operational_event'), 'account_events', type_='unique')
    op.drop_constraint(op.f('uq_auth_operational_event'), 'auth_events', type_='unique')
    op.drop_constraint(op.f('uq_process_operational_event'), 'process_events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_process_operational_event'), 'process_events', ['operational_event_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_auth_operational_event'), 'auth_events', ['operational_event_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_account_operational_event'), 'account_events', ['operational_event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
