"""add refresh_token_version

Revision ID: 20f842000e6d
Revises: 0185b58ff6b2
Create Date: 2026-05-19 16:02:44.253359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f842000e6d'
down_revision: Union[str, Sequence[str], None] = '0185b58ff6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_version', sa.Integer(), nullable=False, server_default = '0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_version')
    # ### end Alembic commands ###
