"""add_subscription_amount_to_clients

Revision ID: 3f8ee520a1c2
Revises: 4acd2ee24692
Create Date: 2026-06-12 09:13:00.417338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8ee520a1c2'
down_revision: Union[str, Sequence[str], None] = '4acd2ee24692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
