"""initial_schema

Revision ID: fb527bec8768
Revises: 
Create Date: 2026-05-14 17:07:00.432303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb527bec8768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('siem_type', sa.String(), nullable=True),
    sa.Column('siem_base_url', sa.String(), nullable=True),
    sa.Column('siem_credentials', sa.String(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('anomaly_visibility_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduler_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('clients_processed', sa.Integer(), nullable=True),
    sa.Column('events_inserted', sa.Integer(), nullable=True),
    sa.Column('anomalies_detected', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_intel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('affected_sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attack_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iocs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_threat_intel_iocs', 'threat_intel', ['iocs'], unique=False, postgresql_using='gin')
    op.create_table('client_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=False),
    sa.Column('graylog_query', sa.String(), nullable=False),
    sa.Column('is_ml_category', sa.Boolean(), nullable=True),
    sa.Column('ml_category', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'query_name', name='uq_client_query_name')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('merchant_request_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('period_covered_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_covered_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('mpesa_receipt_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analyst_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('can_retrain_models', sa.Boolean(), nullable=True),
    sa.Column('can_edit_layer1_rules', sa.Boolean(), nullable=True),
    sa.Column('can_manage_graylog', sa.Boolean(), nullable=True),
    sa.Column('client_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_client', 'audit_log', ['client_id', 'performed_at'], unique=False)
    op.create_index('ix_audit_log_event_type', 'audit_log', ['event_type', 'performed_at'], unique=False)
    op.create_index('ix_audit_log_user', 'audit_log', ['user_id', 'performed_at'], unique=False)
    op.create_table('client_anomaly_visibility',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('toggled_by', sa.Integer(), nullable=True),
    sa.Column('toggled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['toggled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('graylog_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer1_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('backup_path', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trained_by', sa.Integer(), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ml_models_active', 'ml_models', ['client_id', 'category'], unique=True, postgresql_where=sa.text('is_active IS true'))
    op.create_table('operational_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=False),
    sa.Column('event_fingerprint', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_host', sa.String(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_summary', sa.Text(), nullable=True),
    sa.Column('group_key', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_text', sa.Text(), nullable=True),
    sa.Column('issue_raised_by', sa.Integer(), nullable=True),
    sa.Column('issue_raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_fingerprint')
    )
    op.create_index('ix_op_events_client_query', 'operational_events', ['client_id', 'query_name'], unique=False)
    op.create_index('ix_op_events_client_timestamp', 'operational_events', ['client_id', 'timestamp'], unique=False)
    op.create_index('ix_op_events_unanalyzed', 'operational_events', ['client_id', 'analyzed_at'], unique=False, postgresql_where=sa.text('analyzed_at IS NULL'))
    op.create_table('account_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operational_event_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('subject_username', sa.String(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('subject_username_freq', sa.Float(), nullable=True),
    sa.Column('target_username_freq', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rule_reason', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operational_event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_events_client_timestamp', 'account_events', ['client_id', 'timestamp'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operational_event_id', sa.Integer(), nullable=True),
    sa.Column('typed_event_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operational_event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operational_event_id', 'layer', 'anomaly_type', name='uq_anomaly_event_layer_type')
    )
    op.create_index('ix_anomalies_category_layer', 'anomalies', ['category', 'layer'], unique=False)
    op.create_index('ix_anomalies_client_detected', 'anomalies', ['client_id', 'detected_at'], unique=False)
    op.create_index('ix_anomalies_unacknowledged', 'anomalies', ['acknowledged_by'], unique=False, postgresql_where=sa.text('acknowledged_by IS NULL'))
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operational_event_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('target_username_freq', sa.Float(), nullable=True),
    sa.Column('ip_address_freq', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rule_reason', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operational_event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_events_client_timestamp', 'auth_events', ['client_id', 'timestamp'], unique=False)
    op.create_table('event_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['operational_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_view')
    )
    op.create_table('process_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('operational_event_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('subject_username', sa.String(), nullable=True),
    sa.Column('command_line', sa.String(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('subject_username_freq', sa.Float(), nullable=True),
    sa.Column('command_line_freq', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('rule_reason', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['operational_event_id'], ['operational_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_process_events_client_timestamp', 'process_events', ['client_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_process_events_client_timestamp', table_name='process_events')
    op.drop_table('process_events')
    op.drop_table('event_views')
    op.drop_index('ix_auth_events_client_timestamp', table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_index('ix_anomalies_unacknowledged', table_name='anomalies', postgresql_where=sa.text('acknowledged_by IS NULL'))
    op.drop_index('ix_anomalies_client_detected', table_name='anomalies')
    op.drop_index('ix_anomalies_category_layer', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_account_events_client_timestamp', table_name='account_events')
    op.drop_table('account_events')
    op.drop_index('ix_op_events_unanalyzed', table_name='operational_events', postgresql_where=sa.text('analyzed_at IS NULL'))
    op.drop_index('ix_op_events_client_timestamp', table_name='operational_events')
    op.drop_index('ix_op_events_client_query', table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index('ix_ml_models_active', table_name='ml_models', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('ml_models')
    op.drop_table('layer1_rules')
    op.drop_table('graylog_audit')
    op.drop_table('client_anomaly_visibility')
    op.drop_index('ix_audit_log_user', table_name='audit_log')
    op.drop_index('ix_audit_log_event_type', table_name='audit_log')
    op.drop_index('ix_audit_log_client', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('analyst_permissions')
    op.drop_table('users')
    op.drop_table('payments')
    op.drop_table('client_queries')
    op.drop_index('ix_threat_intel_iocs', table_name='threat_intel', postgresql_using='gin')
    op.drop_table('threat_intel')
    op.drop_table('scheduler_status')
    op.drop_table('clients')
    # ### end Alembic commands ###
